name: Build and Push Image in DEV
on:
  pull_request:
  workflow_dispatch:

jobs:
    build-push-docs:
        name: Build and Push Website
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Cache pnpm dependencies
              uses: actions/cache@v3
              with:
                path: ~/.pnpm-store
                key: ${{ runner.OS }}-pnpm-cache-${{ hashFiles('pnpm-lock.yaml') }}
                restore-keys: |
                    ${{ runner.OS }}-pnpm-cache-
            - name: Build with node
              run: |
                npm install -g pnpm@8
                pnpm install --frozen-lockfile
                pnpm run build
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                context: .
                file: Dockerfile
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ghcr.io/fredkiss3/fredkiss-dev:pr-${{ github.event.pull_request.number }},ghcr.io/fredkiss3/fredkiss-dev:${{ github.sha }}
                cache-from: |
                    type=registry,ref=ghcr.io/fredkiss3/fredkiss-dev:pr-${{ github.event.pull_request.number }}
                    type=registry,ref=ghcr.io/fredkiss3/fredkiss-dev:latest
                cache-to: type=inline
            - name: Deploy to Zaneops
              uses: zane-ops/auto-deploy-action@v4
              with:
                  SERVICE_IMAGE: ghcr.io/fredkiss3/fredkiss-dev:${{ github.sha }}
                  DEPLOY_WEBHOOK_URL: ${{ secrets.STAGING_DEPLOY_WEBHOOK_URL }}
                  EXTRA_HEADERS: '{ "CF-Access-Client-Id": "${{ secrets.CF_CLIENT_ID }}", "CF-Access-Client-Secret": "${{ secrets.CF_CLIENT_SECRET }}" }'
    