name: Build and Push Image in DEV
on:
  pull_request:
  workflow_dispatch:

jobs:
    build-push-docs:
        name: Build and Push Website
        runs-on: ubuntu-24.04-arm
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                context: .
                file: Dockerfile
                push: true
                tags: ghcr.io/fredkiss3/fredkiss-dev:pr-${{ github.event.pull_request.number }},ghcr.io/fredkiss3/fredkiss-dev:${{ github.sha }}
                cache-from: |
                    type=registry,ref=ghcr.io/fredkiss3/fredkiss-dev:pr-${{ github.event.pull_request.number }}
                    type=registry,ref=ghcr.io/fredkiss3/fredkiss-dev:latest
                cache-to: type=inline
            - name: Deploy to Zaneops
              uses: zane-ops/auto-deploy-action@v4
              with:
                  SERVICE_IMAGE: ghcr.io/fredkiss3/fredkiss-dev:${{ github.sha }}
                  DEPLOY_WEBHOOK_URL: ${{ secrets.STAGING_DEPLOY_WEBHOOK_URL }}
                  EXTRA_HEADERS: '{ "CF-Access-Client-Id": "${{ secrets.CF_CLIENT_ID }}", "CF-Access-Client-Secret": "${{ secrets.CF_CLIENT_SECRET }}" }'
    